FROM debian:stretch

RUN apt-get update && apt-get install -y --no-install-recommends \
	libgstreamer1.0-0 \
	gstreamer1.0-plugins-base \
	gstreamer1.0-plugins-good \
	gstreamer1.0-plugins-bad \
	gstreamer1.0-plugins-ugly \
	gstreamer1.0-libav \
	gstreamer1.0-doc \
	gstreamer1.0-tools

RUN apt-get install -y net-tools

COPY files/ /root/

COPY scripts/ /usr/local/bin/
RUN chmod a+x /usr/local/bin/*

# Internally uses port 1194/udp, remap using 'docker run -p 443:1194/tcp'
EXPOSE 5600/udp

