#!/bin/sh

gst-launch-1.0 videotestsrc ! x264enc ! h264parse ! rtph264pay ! rtph264depay ! h264parse ! avdec_h264 ! videoconvert ! aasink
# x264enc		H264 Encoder - UGLY
# rtph264pay	Payload-encode H264 video into RTP packets (RFC 3984) - GOOD
# rtph264depay	Extracts H264 video from RTP packets (RFC 3984) - GOOD
# h264parse		Parses H.264 streams - BAD
